#2382 adds a custom title for the News section. Adds custom byline field
BirkbeckCTP/janeway pull request #2387
Opened 2021-09-01 11:11 UTC by ajrbyers

- Adds a new settings for news title
- Adds custom byline
- Updates all themes
- Updates homepage blocks

Closes #2382 and Closes #2381

2021-09-01 13:47 UTC, mauromsl approved these changes

2021-09-01 13:47 UTC, mauromsl commented on src/themes/OLH/templates/core/news/item.html
> +                                <p>{{ news_item.byline }} {% trans "on" %} {{ news_item.posted|date:"Y-m-d" }}</p>
Here we loose the translation of "Posted by"

2021-09-01 13:47 UTC, mauromsl commented on src/themes/OLH/templates/core/news/item.html
> +			<a href="{% url 'core_news_list' %}" class="button success">Back to {{ journal_settings.news.news_title }}</a>
need trans tag for "Back to"

2021-09-01 13:48 UTC, mauromsl requested changes
Just a couple of translation tags needed

2021-09-02 15:38 UTC, ajrbyers commented
Comments addressed in latest commit.

2021-09-03 09:55 UTC, merged