OAI_record now displays full names.
BirkbeckCTP/janeway pull request #2566
Opened 2021-10-29 11:36 UTC by ajrbyers

Closes #2556

2021-11-02 14:00 UTC, ajrbyers commented
@mauromsl we should add this one to RC8!

2021-11-02 14:52 UTC, mauromsl commented
> 
> 
> @mauromsl we should add this one to RC8!

I think so, perhaps move it to a property as you had suggested? (`FrozenAuthor.dc_name_string`)

2021-11-05 11:20 UTC, mauromsl requested changes
couple minor comments

2021-11-05 11:20 UTC, mauromsl commented on src/submission/models.py
> +            name_string += "{}{}, ".format(
The comma here should be added when there is a first name only, no?

We also need to consider the case for `is_corporate` (just call `self.corporate_name`)

2021-11-05 17:21 UTC, mauromsl approved these changes

2021-11-05 17:21 UTC, merged