#2585 removed excess <p> tags.
BirkbeckCTP/janeway pull request #2618
Opened 2021-11-18 14:26 UTC by ajrbyers

- Removes P tags that wrap references
- Closes #2585

2021-12-21 11:03 UTC, mauromsl requested changes

2021-12-21 11:03 UTC, mauromsl commented on src/transform/xsl/default.xsl
> -            <p id="{@id}">
I can see the `template match="mixed-citation">` duplicates this logic, but `element-citation` and `nlm-citation` do not. Those citations wouldn't render any HTML elements with an `id` so I suspect internal links would stop working those objects. Should we remove the redundant <p> tag from mixed-citation instead?

2022-01-13 12:33 UTC, ajrbyers commented
![image](https://user-images.githubusercontent.com/8321378/149330906-99666575-74cf-4c21-9bde-53120e91e5c0.png)
Now looking much cleaner.

2022-01-13 15:41 UTC, mauromsl approved these changes

2022-01-13 15:41 UTC, merged