2701 bugfix empty keywords
BirkbeckCTP/janeway pull request #2754
Opened 2022-02-08 16:17 UTC by mauromsl

2022-02-08 19:59 UTC, joemull requested changes
Just a question about the test names.

2022-02-08 19:59 UTC, joemull commented on src/utils/tests.py
> +        self.assertTrue(journal.keywords.filter(word=expected).exists())
This test has the same name as the one below--does it need a unique name?

2022-02-09 11:01 UTC, ajrbyers approved these changes

2022-02-09 11:01 UTC, ajrbyers commented
@mauromsl looks like tests are failing on jenkins.

2022-02-14 15:36 UTC, ajrbyers commented
test this chuck norris

2022-02-14 15:36 UTC, ajrbyers commented
test this please

2022-02-23 10:46 UTC, merged