#2799 Applies new last modified model to get a better lastmod date for articles.
BirkbeckCTP/janeway pull request #2804
Opened 2022-03-21 15:53 UTC by ajrbyers

2022-03-21 16:05 UTC, mauromsl requested changes
Looks good, I quite like the approach :)

One important comment regarding the calculation of the most recentd date_modified: I think this process needs to be recursive.
Also, we have no tests for the new behaviour

2022-03-21 16:05 UTC, mauromsl commented on src/core/model_utils.py
> +                    dates.append(getattr(object, 'last_modified'))
I suspect this needs to be a recursive call, right? Or have an argument to make it optional at least.

2022-03-21 16:07 UTC, mauromsl commented on src/core/model_utils.py
> +        auto_now_add=False,
We should drop this as well, as want the date_modified to be populated on creation too.

2022-03-21 16:08 UTC, ajrbyers commented
> Looks good, I quite like the approach :)

I'm glad you like the approach you recommended ;)

2022-03-23 11:58 UTC, ajrbyers commented
@mauromsl can we carve some time tomorrow to take a look at the issues we discussed yesterday namely:

1. Recursive call
2. FKs not beeing looked up

2022-03-28 11:39 UTC, merged