2834 preprint review
BirkbeckCTP/janeway pull request #2864
Opened 2022-05-10 09:49 UTC by ajrbyers

2022-06-10 12:17 UTC, mauromsl requested changes
Looks good, just a shame we are duplicating a lot of logic from `review`.
One minor comment inline on the refactor for the settings loader.

It would be good to have some unit tests too

2022-06-10 12:17 UTC, mauromsl commented on src/repository/install.py
> +                if force or not getattr(instance, key):
`getattr` needs to be passed a default return value (e.g `getattr(instance, key, None`). Otherwise it will raise `AttributeError` instead

2022-06-10 12:30 UTC, ajrbyers commented
Add tests for the following:

- [ ] Send an invite
- [ ] Send a review
- [ ] Publish a review comment
- [ ] Unpublish a review comment
- [ ] Any other heavy logic

2022-06-15 08:20 UTC, ajrbyers commented
Tests now passing, yay.

2022-06-15 08:51 UTC, merged