Raise the max_length of Account.username.
BirkbeckCTP/janeway pull request #2978
Opened 2022-06-30 13:17 UTC by gamboz

While migrating accounts from our old systems to Janeway I found 12 of our old accounts with an email longer than 48 characters (in ~120k accounts; our longest is 61 chars).

Since Janeway uses the email to generate the username, and the username has a `max_length` of 48, at the moment I cannot migrate these 12 accounts.

2022-06-30 13:54 UTC, mauromsl requested changes
Thanks @gamboz, lets go even further.
This change should also generate a database migration

2022-06-30 14:13 UTC, gamboz commented on src/core/models.py
> +    username = models.CharField(max_length=84, unique=True, verbose_name=_('Username'))
hmmm... I think I'm missing something...\
The migration that I'm trying to generate doesn't really seem to change anything:
```
ALTER TABLE "core_account" ALTER COLUMN "username" TYPE varchar(254) USING "username"::varchar(254);
```
(must leave now, will check again tomorrow)

2022-07-01 08:49 UTC, gamboz commented on src/core/models.py
> +    username = models.CharField(max_length=84, unique=True, verbose_name=_('Username'))
@mauromsl sorry, false alarm, the migration is fine.

I think I did all the changes:
- [x] set max_length to 254
- [x] generate the migration

2022-07-01 10:59 UTC, mauromsl approved these changes

2022-07-01 10:59 UTC, merged