Adds a new form and widget that implements CC and BCC fields for all emails
BirkbeckCTP/janeway pull request #3121
Opened 2022-09-07 09:22 UTC by mauromsl

2023-07-31 14:41 UTC, joemull commented on src/core/forms/forms.py
> +        subject_setting_name = "subject_" + setting_name
This assumes that subject settings are always named exactly after their corresponding email settings. Have you checked whether that is a safe assumption?

2023-07-31 15:47 UTC, joemull approved these changes
This is a lot of work, and I really appreciate that it establishes type-safe forms and fields that are re-usable for every email interface. In that sense, it's a massive step in the right direction.

As for how to test it, to what extent have you manually tested it? I am a bit unsure how to go about that. 

I added a couple of comments but I don't know how actionable they are.

Overall, I'm guessing this work introduces a few bugs because of how much code it touches, but I'm approving it as I think it's worth moving ahead and figuring out the exceptions as they arise.

2023-08-18 13:48 UTC, ajrbyers commented
I was just looking over this... it looks like it updates review but none of the other workflow elements, is that correct?

2023-10-16 13:00 UTC, ajrbyers requested changes

2023-10-25 12:09 UTC, mauromsl commented
> This is a lot of work, and I really appreciate that it establishes type-safe forms and fields that are re-usable for every email interface. In that sense, it's a massive step in the right direction.
> 
> As for how to test it, to what extent have you manually tested it? I am a bit unsure how to go about that.
> 
> I added a couple of comments but I don't know how actionable they are.
> 
> Overall, I'm guessing this work introduces a few bugs because of how much code it touches, but I'm approving it as I think it's worth moving ahead and figuring out the exceptions as they arise.

I've tweaked the CSS so that at least the field looks the same as any other inputs.
In terms of accessibility, I think our Admin UI is due a whole revamp (including the tagging library) it is not something that pertains this one issue.
![image](https://github.com/BirkbeckCTP/janeway/assets/10760678/1b331ef4-9ad3-44a9-b0cd-805dfeaf6658)

2023-10-25 13:25 UTC, ajrbyers approved these changes

2023-10-25 13:25 UTC, ajrbyers commented
@mauromsl this looks good, but there are 139 failed tests....

2023-10-25 14:20 UTC, mauromsl commented
> @mauromsl this looks good, but there are 139 failed tests....

yeah, the merge with master was missing a tweak required after a refactor. I've also fixed the test data on unit tests that were broken due to my changes. I think the others were already failing on master due to various issues with merged code

2023-10-25 14:43 UTC, merged