Adds support for Collection/Issue level ISBN and exposes it via OAI-PMH and Crossref Deposits
BirkbeckCTP/janeway pull request #3203
Opened 2022-10-11 14:37 UTC by mauromsl

Closes #2762

2022-10-11 14:40 UTC, ajrbyers approved these changes

2022-10-11 14:42 UTC, ajrbyers commented
@mauromsl merge away if tests pass.

2022-10-12 08:30 UTC, joemull requested changes
One variable name to swap out in the Crossref template.

2022-10-12 08:30 UTC, mauromsl commented on src/templates/common/identifiers/crossref_conference.xml
> +                {% else %}
good catch!

2022-10-13 16:59 UTC, merged