Fixes a bug where a carousel limits were not being applied when latest_articles is set.
BirkbeckCTP/janeway pull request #3252
Opened 2022-10-26 14:59 UTC by ajrbyers

2022-10-26 15:01 UTC, ajrbyers commented
test this please

2022-10-27 08:47 UTC, mauromsl requested changes

2022-10-27 08:47 UTC, mauromsl commented on src/core/homepage_elements/carousel/models.py
> +                articles = articles[:self.article_limit]
I think this makes the slice in line 101 redundant now

We also need to apply the same change to the news query below, I think

2022-11-01 10:03 UTC, mauromsl approved these changes

2022-11-01 10:04 UTC, merged