Fix bugs with DOI registration status
BirkbeckCTP/janeway pull request #3268
Opened 2022-11-04 16:04 UTC by joemull

Fixes #3267.

2022-11-08 15:59 UTC, mauromsl requested changes

2022-11-08 17:50 UTC, joemull commented on src/identifiers/logic.py
> +    )
Thanks for these comments--you are right. I've reworked these two functions a bit.

2022-11-09 12:21 UTC, mauromsl approved these changes
This bit is much clearer now, thanks @joemull

2022-11-09 12:24 UTC, mauromsl reviewed
Just one final comment in-line @joemull

2022-11-09 13:02 UTC, joemull commented on src/identifiers/views.py
> +        crossref_status, created = models.CrossrefStatus.objects.get_or_create(
Yeah, this is an attempt to handle a couple possible scenarios, but it is leaky. I've rewritten it for greater clarity to handle the three possible scenarios more cleanly and dependably, including comments.

2022-11-09 15:35 UTC, mauromsl approved these changes
Very clear now, thanks @joemull

2022-11-09 15:36 UTC, merged