Add journal_manager role, and related is_journal_manager checks
BirkbeckCTP/janeway pull request #3332
Opened 2022-12-21 19:11 UTC by hardyoyo

- Add journal_manager role migration
- Add is_journal_manager check to Account model
- Add journal_manager_user_required decorator for later convenience
- Add checks for journal_manager role to portions of group_journal,
group_submission, configurator and licenses admin templates

fixes #495
fixes #3232

2022-12-21 19:45 UTC, hardyoyo commented
Oh, I can see two things wrong with this PR: it accidentally includes an unrelated commit, and it has a typo mention of an unrelated issue. I'll fix those things and push again

2023-01-11 17:20 UTC, ajrbyers commented
@hardyoyo you should be able to tweak the create function for this Serializer to stop Editors for assigning the role.

https://github.com/BirkbeckCTP/janeway/blob/d1cd3c9b98baf39197cecda4a75da0d1c2064798/src/api/serializers.py#L116

2023-01-11 21:31 UTC, hardyoyo commented
word is this is still not quite right, @justingonder will post with more details soon, do not merge, I'll mark this as a draft

2023-01-17 15:20 UTC, hardyoyo commented
Marked this as ready for review last week (removed the "draft" flag), as you can see from the flurry of commits, there were a fair number of tiny bugs to fix. I can squash all of the commits if that would make reviewing the PR easier. Let me know if you'd like this squashed.

2023-01-17 15:53 UTC, mauromsl requested changes
I've added a couple of comments about the implementation inline.

As for the introduction of this new role, I don't think it is a simple change to introduce and needs a bit more thought:
Do we want to disallow editors from accessing the "All settings" interface? I think this approach is a bit extreme and I would rather opt for a more configurable approach. Instead, I would add a new attribute/row to the `'core.Setting'` model that determines the roles which can alter a given setting. The `journal_defaults.json` file would provide the default values while allowing individual installs to alter our defaults. Janeway. 
My reasoning is based around 3  lines of thought:
 1. I believe this approach would be more flexible towards the introduction of new built-in roles (e.g. managing editor vs editor) 
  2. Configurable permission settings would also take us one step closer towards the creation of custom roles (e.g. web content editor, review manager...). 
  3. A flexible system like the proposed would allow us to not turn this feature into a breaking change for folks currently using Janeway, while also allowing for the conditions of the use case presented here to be met.
  
Another discussion point is to decide what areas of the system should be accessible to a user who is granted the `journal-manager` role but not the editor role, since I can't see that case covered in this PR
  
Finally, we'd need to update the documentation and editor guides accordingly, clearly stating what is on/offlimits moving forward for the editor role. Some of the training videos will need re-recording too.

2023-01-17 15:53 UTC, mauromsl commented on src/api/serializers.py
> +            raise serializers.ValidationError({"role": "You cannot add a user as a " + role.slug + " via the API."})
I'd feel more comfortable if this logic took place inside a validator except of happening ad-hoc at `create` time:
https://www.django-rest-framework.org/api-guide/validators/

2023-01-17 15:53 UTC, mauromsl commented on src/templates/admin/submission/manager/licenses.html
> +            {% if user_is_journal_manager %}
as above, we'd need backend validation too

2023-01-17 15:53 UTC, mauromsl commented on src/templates/admin/submission/manager/configurator.html
> +                {% if user_is_journal_manager %}
While this invocation will stop the inner HTML from rendering, it won't actually validate on the backend, we'd need validation to take place there.

2023-01-31 21:18 UTC, closed without merging

2023-01-31 21:18 UTC, hardyoyo commented
replaced by https://github.com/BirkbeckCTP/janeway/pull/3374 ... closing