Fixes a bug that stopped user details from showing on the merge users page
BirkbeckCTP/janeway pull request #3356
Opened 2023-01-19 10:16 UTC by ajrbyers

2023-01-19 10:37 UTC, mauromsl requested changes
@ajrbyers do we not need to also traverse any additional pages that may be available through the API?

2023-01-19 11:40 UTC, ajrbyers commented
> @ajrbyers do we not need to also traverse any additional pages that may be available through the API?

could do… but 100 records should be sufficient.

2023-01-19 14:24 UTC, mauromsl commented
> > @ajrbyers do we not need to also traverse any additional pages that may be available through the API?
> 
> could do… but 100 records should be sufficient.

Ah I see what you mean, because we use it for search, the user will always expand the query to narrow down the results beyond 100 anyways

2023-01-25 07:27 UTC, mauromsl approved these changes

2023-01-25 07:27 UTC, merged