#3289 remove ID from section __str__
BirkbeckCTP/janeway pull request #3459
Opened 2023-03-27 16:39 UTC by ajrbyers

- Updates the Section model's __str__ method to remove the PK
- Closes #3289

2023-05-18 07:15 UTC, mauromsl approved these changes

2023-05-18 07:20 UTC, mauromsl requested changes

2023-05-18 07:20 UTC, mauromsl commented on src/submission/models.py
> +        return self.name
`Section.name` is nullable, which could lead to this method returning a `NoneType` object. We should return either an empty string, a sentinel value or a string with the section ID in that case

There is also a test case failing with this change.

2023-05-18 07:54 UTC, ajrbyers commented
Updates pushed, thanks @mauromsl

2023-05-19 09:37 UTC, mauromsl approved these changes

2023-05-19 09:37 UTC, merged