#1471 pass decisions through to the warning view so it can redirect the user properly
BirkbeckCTP/janeway pull request #3465
Opened 2023-03-29 12:18 UTC by ajrbyers

- Passes the decision a user makes into the warning page so it can then redirect the user on an override
- Closes #1471

2023-05-18 10:50 UTC, mauromsl requested changes

2023-05-18 10:50 UTC, mauromsl commented on src/review/urls.py
> +    re_path(r'^article/(?P<article_id>\d+)/decision/(?P<decision>accept|decline|undecline|review)/access_denied/$', views.review_warning, name='review_warning'),
Can we generate these out of the new Enum constants? You should be able to with something like `"|".join(item.value for item in review.const.ReviewDecisions)`

```

2023-05-18 10:52 UTC, mauromsl requested changes
Just a couple minor suggestions inline

2023-05-18 10:52 UTC, mauromsl commented on src/review/views.py
> +        if decision == 'review':
we should use constants here too

2023-05-18 10:52 UTC, mauromsl commented on src/security/decorators.py
> +        decision = kwargs.get('decision', 'review')
we should use constants here

2023-05-23 11:40 UTC, ajrbyers commented
Closed in favour of https://github.com/BirkbeckCTP/janeway/pull/3570

2023-05-23 11:40 UTC, closed without merging