965 the old submission_competing_interests has been removed, this is controlled by submission configuration
BirkbeckCTP/janeway pull request #3549
Opened 2023-05-16 10:10 UTC by ajrbyers

- Note: As the interface required both settings to be enabled in order to work we can safely just replace `submission_competing_interests` with the configuration equivalent. Anyone actually using this setting wont see any difference.
- Closes #965

2023-05-18 11:47 UTC, mauromsl reviewed
Looks good, but there are a couple of unrelated changes leaked from another branch

2023-05-18 11:47 UTC, mauromsl commented on src/journal/migrations/0060_alter_journal_code.py
> +            field=models.CharField(help_text='Short acronym for the journal. Used as part of the journal URLin path mode and to uniquely identify the journal', max_length=40, unique=True),
This leaked from another branch

2023-05-18 11:47 UTC, mauromsl commented on src/journal/models.py
> +    code = models.CharField(max_length=40, unique=True, help_text=gettext(
This leaked from another branch

2023-05-19 11:14 UTC, joemull commented on src/submission/forms.py
> +
Does this belong on this branch? And does it need to be indented further so that it is part of the for loop?

2023-05-19 11:18 UTC, joemull requested changes
There are still leaked changes, unless I'm mistaken.

2023-05-19 11:21 UTC, ajrbyers commented
Commits in to revert weirdness.

2023-05-19 11:58 UTC, joemull requested changes

2023-05-19 12:13 UTC, joemull approved these changes

2023-05-23 09:12 UTC, ajrbyers commented
Closed in favour of https://github.com/BirkbeckCTP/janeway/pull/3569

2023-05-23 09:12 UTC, closed without merging