Copyediting related to press site #3711
BirkbeckCTP/janeway pull request #3712
Opened 2023-09-13 14:09 UTC by joemull

Closes #3711.

2023-09-15 10:43 UTC, ajrbyers approved these changes

2024-01-25 09:48 UTC, mauromsl requested changes

2024-01-25 09:48 UTC, mauromsl commented on src/core/forms/forms.py
> +    password_2 = forms.CharField(widget=forms.PasswordInput, label=_('Confirm Password'))
Can we also update "Password 2" entries on .po files to avoid reverting this translation on live installs?

2024-01-25 13:17 UTC, joemull commented
Jenkins: test this please

2024-01-25 14:50 UTC, mauromsl approved these changes

2024-01-25 14:50 UTC, merged