Clean up meta tags block #3692
BirkbeckCTP/janeway pull request #3714
Opened 2023-09-13 14:43 UTC by joemull

Closes #3692.

2023-09-15 10:37 UTC, ajrbyers requested changes
See comment inline. The new templatetag added isn't used, is this PR incomplete?

2023-09-15 10:37 UTC, ajrbyers commented on src/core/templatetags/fqdn.py
> +def build_absolute_uri(context, relative_url, *args):
As far as I can tell this templatetag is never used.

2024-01-16 10:07 UTC, ajrbyers approved these changes

2024-01-25 09:16 UTC, mauromsl approved these changes

2024-01-25 09:17 UTC, merged