Management command for sending emails
BirkbeckCTP/janeway pull request #3812
Opened 2023-12-07 14:23 UTC by joemull

Closes #3809.

2023-12-08 09:09 UTC, mauromsl requested changes
Thanks Joe, this will be very useful I'm sure. A couple of suggestions in line

2023-12-08 09:09 UTC, mauromsl commented on src/utils/management/commands/send_email.py
> +        body_file = os.path.join(settings.BASE_DIR, options['body'])
This is a bit weird, usually with command line programs you would expect the relative path to be calculated from the current working directory (default behaviour of Python's `open()`)

2023-12-08 09:09 UTC, mauromsl commented on src/utils/management/commands/send_email.py
> +        logger.info(self.style.SUCCESS('Email sent'))
can we add a short sleep timer (a fraction of a second) here in between batches? It is  particularly important when using email backends like Mailgun, to make sure we don't overrun limits

2023-12-11 14:28 UTC, ajrbyers approved these changes

2023-12-11 14:28 UTC, merged