#3382 author dashboard update to link to article history
BirkbeckCTP/janeway pull request #3823
Opened 2023-12-11 13:03 UTC by StephDriver

After publication, both the live article and the article history (e.g. peer reviews) should be accessible from the author dashboard.

Updated the author dashboard:
- column heading 'View Live' changed to 'View
- button 'View Live' changed to 'Live'
- button 'History' added before 'Live' in 'View' Column which links to same page as 'View Status' does before publication (copy/paste of code for View Status).

closes #3382

2024-05-01 10:41 UTC, ajrbyers requested changes
I think in this instance the comments can be removed but this looks good otherwise.

2024-05-01 15:08 UTC, StephDriver commented
comments removed as requested

2024-05-28 10:23 UTC, ajrbyers approved these changes

2024-06-04 09:33 UTC, mauromsl commented
jenkins: add to whitelist

2024-07-17 11:50 UTC, joemull requested changes
The History and Live buttons are working but the review link is not: 

![image](https://github.com/user-attachments/assets/36708112-8c97-4a10-8b23-cc3ba5261072)

This gets to the larger question of what the author should be able to see, because so far we have only expected authors to view assignments in progress, not retrospectively. 

I think this feature may need to go back to backlog refinement so we can decide what the author should be able to see after assignments are closed. I think there's a case to be made that they should see the full history of assignments, but that will require editing each related view and template to work out the display of past information. More detail inline.

2024-07-17 11:50 UTC, joemull commented on src/templates/admin/elements/core/author_dashboard.html
> +                                {% endfor %}
I think this is not the right thing to check for and display here. It just checks for in-progress revision requests, but in most cases there won't be any of those by the time the article is published. 

It should get completed requests, i.e. `article.completed_revision_requests`.

I think it should also check for completed copyediting reviews, via a new function that doesn't yet exist called `article.completed_author_copyedits`, based on `article.active_author_copyedits`. Together these will mirror what is happening here for active requests:

https://github.com/BirkbeckCTP/janeway/blob/bc2635fab46f45873860c78a2324f241b0bfa13f/src/templates/admin/elements/core/author_dashboard.html#L59-L69

However, the views controlling those links expect that the author only ever views an active request. They raise a 404 if the request has been completed:

https://github.com/BirkbeckCTP/janeway/blob/3f49d4b36d19a7591452461837b498e232b3e2a6/src/review/views.py#L1942-L1948

https://github.com/BirkbeckCTP/janeway/blob/3f49d4b36d19a7591452461837b498e232b3e2a6/src/copyediting/views.py#L718-L723

So we need to modify those views and think through what the author should see when viewing a completed request.

The one other complication is there could be more than one revision request or more than one copyediting review, so we need to alter the labels so the user can tell them apart. Maybe add the ID of the review after the label?

![image](https://github.com/user-attachments/assets/5cb139d5-a2b1-47dd-833e-074ee072f5a1)

2024-07-17 11:53 UTC, joemull commented
> I think this feature may need to go back to backlog refinement so we can decide what the author should be able to see after assignments are closed. I think there's a case to be made that they should see the full history of assignments, but that will require editing each related view and template to work out the display of past information.

On second thought maybe one for design?

2024-08-01 09:22 UTC, joemull commented
@ajrbyers we discussed this in backlog refinement and want to send it back to you for another review. Do you agree it might be best to close this PR until we can redefine the issue?

2024-08-07 10:44 UTC, ajrbyers commented
> @ajrbyers we discussed this in backlog refinement and want to send it back to you for another review. Do you agree it might be best to close this PR until we can redefine the issue?

Sure. I've shifted the original Issue to Needs Design in Triage.

2024-08-07 10:44 UTC, closed without merging