#3906 un-nest labels and inputs in themes
BirkbeckCTP/janeway pull request #3908
Opened 2024-01-24 09:54 UTC by StephDriver

all file search for labels which nested their input and only two were found, both in theme templates marked as depreciated in 1.5.1.

Labels elsewhere looked un-nested, and hence avoiding this issue.

Closes #3906

2024-02-15 20:12 UTC, ajrbyers requested changes
This is okay, does the display remain the same after the change?

2024-02-15 20:12 UTC, ajrbyers commented on src/themes/OLH/templates/elements/journal/article_filter_form.html
> +        Hi there
This needs to be removed.

2024-03-05 15:02 UTC, StephDriver commented on src/themes/OLH/templates/elements/journal/article_filter_form.html
> +        Hi there
done

2024-03-08 11:12 UTC, ajrbyers approved these changes

2024-03-14 08:43 UTC, joemull reviewed
Just thought I'd mention this template is no longer used, to my knowledge. I added this deprecation note recently when I switched this interface to using a class-based view:

https://github.com/BirkbeckCTP/janeway/blob/9fcbbe87b917bf3c4ce1d64b85d579f7c0634069/src/themes/OLH/templates/elements/journal/article_filter_form.html#L1

Maybe I should have just deleted the template? I wasn't confident doing so without more front-end tests in place.

2024-03-14 09:28 UTC, joemull commented
@ajrbyers Brilliant! I've added an issue for it.

2024-03-14 09:28 UTC, joemull approved these changes

2024-03-14 09:29 UTC, merged