Update psycopg2-binary version
BirkbeckCTP/janeway pull request #4082
Opened 2024-04-08 10:48 UTC by joemull

During a recent fresh installation I ran into an issue with pip install
of psycopg2-binary. Version 2.8.6 uses an outdated installation method.

I am proposing bumping this to 2.9.8. I've read the changelog and don't
believe there are any breaking changes for us between these versions.
Version 2.9.9 drops support for python 3.6, so I don't think we should
go that far until we drop python 3.6.

2024-04-15 16:20 UTC, ajrbyers commented
@joemull why is this merging into [4072-django-4-2](https://github.com/BirkbeckCTP/janeway/tree/4072-django-4-2) ?

2024-04-16 14:35 UTC, joemull commented
> @joemull why is this merging into [4072-django-4-2](https://github.com/BirkbeckCTP/janeway/tree/4072-django-4-2) ?

Sorry, I guess that's a bit confusing. I saw Mauro was updating the requirements file, is why. I'll go ahead and change the branch to master.

2024-04-16 14:43 UTC, mauromsl requested changes
Hey @joemull, I had a look at the changelog for psycopg2 and I think it is safe to do this upgrade. There is something wrong with your branch base though and it is bringing other commits with it. Can you rebase your branch first?

2024-04-19 08:07 UTC, mauromsl approved these changes

2024-04-19 08:08 UTC, mauromsl commented
blocked by #4073

2024-04-26 08:46 UTC, merged