Fixes a bad typo on the editor's revision interface.
BirkbeckCTP/janeway pull request #4161
Opened 2024-05-02 14:41 UTC by ajrbyers

2024-05-02 14:44 UTC, S-Haime approved these changes
Good one (and welp that one is a bit awkward indeed!)

2024-05-07 09:01 UTC, joemull requested changes

2024-05-07 09:01 UTC, joemull commented on src/templates/admin/review/revision/view_revision.html
> +                    <p>The author has not writen a covering letter.</p>
"written" needs two Ts.

Also let's fix line 64:
```html
<p>The author write a response letter.</p>
```

2024-05-07 09:15 UTC, joemull approved these changes

2024-05-07 09:15 UTC, merged