When using send_user_email a log dict entry is now passed to send_email.
BirkbeckCTP/janeway pull request #4198
Opened 2024-05-23 09:14 UTC by ajrbyers

Closes #4197

2024-05-23 15:23 UTC, mauromsl approved these changes

2024-05-23 15:25 UTC, mauromsl requested changes

2024-05-23 15:25 UTC, mauromsl commented on src/journal/views.py
> +        }
shouldn't this be moved to below the check for `form.is_valid` and after the email is sent?

2024-05-28 10:23 UTC, ajrbyers commented
@mauromsl I've added the requested change.

2024-05-31 09:11 UTC, joemull approved these changes

2024-06-04 08:25 UTC, merged