A warning will show in prepublication when an article has no license set.
BirkbeckCTP/janeway pull request #4219
Opened 2024-05-31 10:06 UTC by ajrbyers

Closes #2270 

<img width="351" alt="image" src="https://github.com/BirkbeckCTP/janeway/assets/8321378/dd3270d8-0ed4-4468-a61d-92fe63c7dee7">

2024-05-31 10:46 UTC, mauromsl approved these changes

2024-05-31 10:49 UTC, ajrbyers commented
Note: discussed with @mauromsl and decided that adding a warning for non CC licenses was a too opinionated.

2024-06-04 09:12 UTC, ajrbyers commented
> One of these doesn't have `target="_blank"`. Is that intentional?
> 
> The projected issue one (not changed in this PR) doesn't have one either.

Thanks Joe, I've added that in. The projected issue link opens a modal so doesn't require one.

2024-06-04 14:49 UTC, joemull requested changes
"Opens in new tab" is nice, but this syntax `sr-only` is not used in foundation, is it?

https://sites.get.foundation/visibility.html#accessibility

It looks like it's included in `font-awesome`, but that's not what we want to draw on here, right?

2024-06-04 14:59 UTC, joemull approved these changes

2024-06-04 14:59 UTC, merged