Editor review complete email now contains additionally information and a direct link
BirkbeckCTP/janeway pull request #4250
Opened 2024-06-04 15:00 UTC by ajrbyers

There were 6 close variants of this text.

Closes #1829

2024-06-26 13:46 UTC, mauromsl approved these changes

2024-06-27 14:00 UTC, joemull requested changes
Nitpick on copywriting.

2024-07-12 08:55 UTC, joemull approved these changes

2024-07-15 08:39 UTC, joemull commented
@ajrbyers this will now cause a migration mismatch. Could we rebase it locally and change the migration dependency to `0095_auto_20240605_1024`?

2024-07-15 11:05 UTC, ajrbyers commented
Closed this in favour of https://github.com/BirkbeckCTP/janeway/pull/4324

2024-07-15 11:05 UTC, closed without merging