Close incomplete review assignments when an article is rejected
BirkbeckCTP/janeway pull request #4305
Opened 2024-06-27 19:38 UTC by everreau

Related issue: https://github.com/BirkbeckCTP/janeway/issues/4251

We found that open review counts for some reviewers were higher than expected because incomplete reviews from rejected articles were still open.

- Close incomplete review assignments when an article is rejected
- Add a callout to the "decline" email form that tells the user this will happen.

2024-06-27 19:38 UTC, Bbkctp commented
Can one of the admins verify this patch?

2024-06-28 08:07 UTC, ajrbyers commented
Jenkins: test this please

2024-07-03 15:19 UTC, joemull requested changes
Thank you for this @everreau--all the logic looks good to me, and we always appreciate a test!

Could we just put the line lengths down to PEP-8's max width of 80 chars? I know Janeway has lots of long lines but we are currently working on getting that down by linting the things we change. (We want to implement Black at some point but it is hard finding the right moment.)

2024-07-08 18:20 UTC, everreau commented
@joemull done.  I'm assuming this only applies to python code not templates.

2024-07-10 10:51 UTC, joemull approved these changes

2024-07-10 10:52 UTC, joemull commented
> @joemull done. I'm assuming this only applies to python code not templates.

Thanks. Yes for now just Python, though we are considering the same max width of 80 for HTML and CSS.

2024-07-10 10:56 UTC, joemull commented
Closes https://github.com/BirkbeckCTP/janeway/issues/4251.

2024-07-10 11:04 UTC, ajrbyers requested changes
I've requested a change but also have a thought to discuss. When we withdraw a review manually we also email the reviewer:

https://github.com/BirkbeckCTP/janeway/blob/78dd8f015293257b6f0e7c551fd2af29a1a35c3f/src/review/views.py#L1548-L1575

Should this process automatically send an email using this tempalte to the reviewers as well?

2024-07-17 17:23 UTC, everreau commented on src/submission/models.py
> +        self.incomplete_reviews().update(decision='withdrawn',
done

2024-07-17 17:25 UTC, everreau commented
> I've requested a change but also have a thought to discuss. When we withdraw a review manually we also email the reviewer:
> 
> https://github.com/BirkbeckCTP/janeway/blob/78dd8f015293257b6f0e7c551fd2af29a1a35c3f/src/review/views.py#L1548-L1575
> 
> Should this process automatically send an email using this tempalte to the reviewers as well?

I asked Charlotte about this and she says if it's just an auto-notification she'd rather not.  It's more likely to be interpreted as spam.

2024-07-23 08:00 UTC, ajrbyers approved these changes

2024-07-23 08:00 UTC, merged