Adds a skip to content link to all themes that is tab navigable
BirkbeckCTP/janeway pull request #4332
Opened 2024-07-22 11:23 UTC by ajrbyers

- Adds a new common template
- Replaces existing skip to content for clean
- Adds ID to `<main>`
- Closes #3932 
<img width="538" alt="Screenshot 2024-07-22 at 12 20 43" src="https://github.com/user-attachments/assets/0c675036-cbb3-4f49-89ba-380871369d27">
<img width="509" alt="Screenshot 2024-07-22 at 12 20 32" src="https://github.com/user-attachments/assets/40112c5c-aebd-4884-96de-93f7cad2b285">
<img width="1441" alt="Screenshot 2024-07-22 at 12 20 16" src="https://github.com/user-attachments/assets/43763872-6444-4361-85fc-fce0632c32da">

2024-07-23 15:54 UTC, StephDriver commented
Andy, I'm not too keen on this.  Pretty much everywhere I've seen "skip to content" implemented, it doesn't appear over the top of existing content.  I've seen some places do it by having strategically positioned whitespace, others by dynamically scrolling the whole page down or sideways to make space for new accessible menu items like this.   Here's an example of the functionality on the Access to Work site from .gov.uk - i.e. aimed at disabled users. (tabs are highlighting in yellow)

https://github.com/user-attachments/assets/eb8b004d-6f4a-400a-b3d9-36803bf4e9d0

2024-07-23 15:55 UTC, StephDriver requested changes
see comment on Conversation page - I don't think having this over the top of other content is an accessible implementation.  It won't just be people who can't see the page who use this functionality. It shouldn't be obscuring other content.

2024-07-24 09:10 UTC, ajrbyers commented
<img width="1493" alt="Screenshot 2024-07-24 at 10 05 23" src="https://github.com/user-attachments/assets/b95a3b5d-99fa-4271-9ca5-2de4470968ee">
<img width="657" alt="Screenshot 2024-07-24 at 10 05 17" src="https://github.com/user-attachments/assets/36bc511c-ac19-4ad5-abe6-fd47e6708899">
<img width="1416" alt="Screenshot 2024-07-24 at 10 05 57" src="https://github.com/user-attachments/assets/7a6dad37-b5a8-4c89-ad64-954479c43241">
<img width="635" alt="Screenshot 2024-07-24 at 10 05 52" src="https://github.com/user-attachments/assets/0b8dca2c-aba2-43eb-8cbb-4e046894bf22">
<img width="1410" alt="Screenshot 2024-07-24 at 10 05 32" src="https://github.com/user-attachments/assets/41a63822-bdd4-431a-92f8-136838745acb">
<img width="661" alt="Screenshot 2024-07-24 at 10 05 42" src="https://github.com/user-attachments/assets/9aa36478-dd4a-4f0b-a35f-0934bb84ff9b">

2024-07-26 10:36 UTC, StephDriver requested changes
I don't think the behaviour here is quite right yet. 

When I tested this, while the "skip to content" link did move the page (✅ ) if I then tab again, I'm back at the top at the next item after skip to content.  So basically having had the skip, I can't continue from that point ( :x: ).  After skipping the next tab item should be the next one after the start of hte main content, not taking me back to the top of the page.

I've tested this on Chrome with a press site and journal site - finding the same behaviour on both.

2024-07-26 10:37 UTC, ajrbyers commented
> I don't think the behaviour here is quite right yet.
> 
> When I tested this, while the "skip to content" link did move the page (✅ ) if I then tab again, I'm back at the top at the next item after skip to content. So basically having had the skip, I can't continue from that point ( ❌ ). After skipping the next tab item should be the next one after the start of hte main content, not taking me back to the top of the page.
> 
> I've tested this on Chrome with a press site and journal site - finding the same behaviour on both.

Which theme did you test this with?

2024-07-26 10:41 UTC, StephDriver commented
> Which theme did you test this with?

OLH.

I've just tried Clean and Material - and those are both fine.  So I think just an OLH issue?

2024-07-26 10:42 UTC, ajrbyers commented
> > Which theme did you test this with?
> 
> OLH.
> 
> I've just tried Clean and Material - and those are both fine. So I think just an OLH issue?

Yeah I just tested it there too. I think its intercepting the click so the anchor link isn't set and the focus doesn't move.

2024-07-26 10:47 UTC, StephDriver commented
I'll leave it with you then - I think that's the only problem remaining - from what I can see the rest of the requirements are there:


✅ link is the first focusable control on the Web page.
✅  description of the link communicates that it links to the main content.
✅ (the link is either always visible - No) or visible when it has keyboard focus (Yes).
✅  activating the link moves the focus to the main content.
( :x: OLH, ✅ Clean & Material) after activating the link, the keyboard focus has moved to the main content.

from [WCAG G1](https://www.w3.org/TR/WCAG20-TECHS/G1.html)

2024-08-01 13:25 UTC, ajrbyers commented
@StephDriver I've updated OLH's JS to stop it intercepting the anchor hash being added to the URL bar. All looks okay now. To test this locally you will need to run the `build_assets` command.

2024-08-05 13:16 UTC, StephDriver commented
I have been testing it with random pages, and this time that ended up being a homepage, where it skipped to a search bar rather than the start of the main content.  But it works fine on an article page, and on the list of articles too.  I wonder whether at this point it would be best to implement this solution, since it seems fine for 99% of the site, and then raise a new issue for reviewing its functionality on the landing page? 

I am suggesting that because I think the problem is actually with the landing page structure not this issue.  The landing page's main content starts with a search bar, before having a heading. Rather than change this new functionality to look for the heading which isn't where it should be on that page, I'd rather improve the structure of the landing page.

2024-08-05 13:17 UTC, StephDriver approved these changes
I have left a comment on the behaviour on landing pages, which I think should be addressed separately.  Otherwise I'm happy to approve this.

2024-08-07 09:58 UTC, joemull approved these changes

2024-08-07 09:58 UTC, merged